1.Design a distributed application using RPC for remote computation where client submits an integer value to the server and server calculates factorial and returns the result to the client program

In [ ]:
from xmlrpc.server import SimpleXMLRPCServer
import math

def factorial(n):
    result = math.factorial(n)
    return result

server = SimpleXMLRPCServer(("localhost", 8000))
print("Server is running on port 8000...")

server.register_function(factorial, "factorial")
server.serve_forever()

In [ ]:
# Client
import xmlrpc.client

client = xmlrpc.client.ServerProxy("http://localhost:8000/")

n = int(input("Enter an integer value to calculate its factorial: "))

result = client.factorial(n)
print(f"The factorial of {n} is: {result}")

2.Design a distributed application using RMI for remote computation where client submits two strings to the server and server returns the concatenation of the given strings.

In [ ]:
# Server @2
import Pyro4
@Pyro4.expose
class StringConcatenator:
    def concatenate_strings(self, str1, str2):
        return str1 + str2

daemon = Pyro4.Daemon()
uri = daemon.register(StringConcatenator)

print("Server is running. URI:", uri)

daemon.requestLoop()

In [ ]:
# Client@2
import Pyro4

uri = input("Enter the URI of the StringConcatenator object: ")
concatenator = Pyro4.Proxy(uri)

str1 = input("Enter the first string: ")
str2 = input("Enter the second string: ")

result = concatenator.concatenate_strings(str1, str2)
print(f"The concatenated string is: {result}")

3.Implement Union, Intersection, Complement and Difference operations on fuzzy sets. Also create fuzzy relations by Cartesian product of any two fuzzy sets and perform max-min composition on any two fuzzy relations.

In [1]:
import numpy as np
 
# Function to perform Union operation on fuzzy sets
def fuzzy_union(A, B):
    return np.maximum(A, B)
 
# Function to perform Intersection operation on fuzzy sets
def fuzzy_intersection(A, B):
    return np.minimum(A, B)
 
# Function to perform Complement operation on a fuzzy set
def fuzzy_complement(A):
    return 1 - A
 
# Function to perform Difference operation on fuzzy sets
def fuzzy_difference(A, B):
    return np.maximum(A, 1 - B)
 
# Function to create fuzzy relation by Cartesian product of two fuzzy sets
def cartesian_product(A, B):
    return np.outer(A, B)
 
# Function to perform Max-Min composition on two fuzzy relations
def max_min_composition(R, S):
    return np.maximum(np.minimum.outer(R, S), np.minimum.outer(S, R))
 
# Example usage
A = np.array([0.2, 0.4, 0.6, 0.8])  # Fuzzy set A
B = np.array([0.3, 0.5, 0.7, 0.9])  # Fuzzy set B
 
# Operations on fuzzy sets
union_result = fuzzy_union(A, B)
intersection_result = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
difference_result = fuzzy_difference(A, B)
 
print("Union:", union_result)
print("Intersection:", intersection_result)
print("Complement of A:", complement_A)
print("Difference:", difference_result)
 
# Fuzzy relations
R = np.array([0.2, 0.5, 0.4])  # Fuzzy relation R
S = np.array([0.6, 0.3, 0.7])  # Fuzzy relation S
 
# Cartesian product of fuzzy relations
cartesian_result = cartesian_product(R, S)
 
# Max-Min composition of fuzzy relations
composition_result = max_min_composition(R, S)
 
print("Cartesian product of R and S:")
print(cartesian_result)
 
print("Max-Min composition of R and S:")
print(composition_result)


Union: [0.3 0.5 0.7 0.9]
Intersection: [0.2 0.4 0.6 0.8]
Complement of A: [0.8 0.6 0.4 0.2]
Difference: [0.7 0.5 0.6 0.8]
Cartesian product of R and S:
[[0.12 0.06 0.14]
 [0.3  0.15 0.35]
 [0.24 0.12 0.28]]
Max-Min composition of R and S:
[[0.2 0.5 0.4]
 [0.5 0.3 0.5]
 [0.4 0.5 0.4]]


4.Write code to simulate requests coming from clients and distribute them among the servers using the load balancing algorithms

In [3]:
import random

class LoadBalancer:
    def __init__(self, servers):
        self.servers = servers
        self.num_servers = len(servers)
        self.round_robin_index = 0

    def round_robin(self):
        server = self.servers[self.round_robin_index]
        self.round_robin_index = (self.round_robin_index + 1) % self.num_servers
        return server

    def random_selection(self):
        return random.choice(self.servers)

# Example usage:
servers = ['Server1', 'Server2', 'Server3']
lb_round_robin = LoadBalancer(servers)
lb_random = LoadBalancer(servers)

# Simulate requests coming from clients
num_requests = 20
print("Round Robin Load Balancing:")
for i in range(num_requests):
    server = lb_round_robin.round_robin()
    print(f"Request {i+1} directed to {server}")

print("\nRandom Load Balancing:")
for i in range(num_requests):
    server = lb_random.random_selection()
    print(f"Request {i+1} directed to {server}")

Round Robin Load Balancing:
Request 1 directed to Server1
Request 2 directed to Server2
Request 3 directed to Server3
Request 4 directed to Server1
Request 5 directed to Server2
Request 6 directed to Server3
Request 7 directed to Server1
Request 8 directed to Server2
Request 9 directed to Server3
Request 10 directed to Server1
Request 11 directed to Server2
Request 12 directed to Server3
Request 13 directed to Server1
Request 14 directed to Server2
Request 15 directed to Server3
Request 16 directed to Server1
Request 17 directed to Server2
Request 18 directed to Server3
Request 19 directed to Server1
Request 20 directed to Server2

Random Load Balancing:
Request 1 directed to Server1
Request 2 directed to Server2
Request 3 directed to Server2
Request 4 directed to Server3
Request 5 directed to Server3
Request 6 directed to Server2
Request 7 directed to Server3
Request 8 directed to Server2
Request 9 directed to Server3
Request 10 directed to Server2
Request 11 directed to Server1
Reque

5.Implementation of Clonal selection algorithm using Python

In [2]:
import random

# Initialize the population with random antibodies
def initialize_population(population_size, antibody_length):
    population = []
    
    for _ in range(population_size):
        antibody = [random.choice([0, 1]) for _ in range(antibody_length)]
        population.append(antibody)
    
    return population

# Calculate affinity of an antibody
def calculate_affinity(antibody):
    return sum(antibody)

# Select the antibodies with highest affinity
def select_best_antibodies(population, clone_size):
    sorted_population = sorted(population, key=calculate_affinity, reverse=True)
    return sorted_population[:clone_size]

# Mutate the selected antibodies
def mutate_antibodies(antibodies, mutation_rate):
    for antibody in antibodies:
        for i in range(len(antibody)):
            if random.random() < mutation_rate:
                antibody[i] = 1 - antibody[i]
    
    return antibodies

# Perform clonal selection algorithm
def clonal_selection_algorithm(population_size, antibody_length, clone_size, mutation_rate, generations):
    population = initialize_population(population_size, antibody_length)
    
    for _ in range(generations):
        best_antibodies = select_best_antibodies(population, clone_size)
        mutated_antibodies = mutate_antibodies(best_antibodies, mutation_rate)
        
        population += mutated_antibodies
    
    return max(population, key=calculate_affinity)

# Example usage
population_size = 100
antibody_length = 10
clone_size = 10
mutation_rate = 0.1
generations = 100

result = clonal_selection_algorithm(population_size, antibody_length, clone_size, mutation_rate, generations)
print("Best Antibody:", result)


Best Antibody: [1, 1, 0, 0, 1, 0, 0, 1, 1, 1]


7.To apply the artificial immune pattern recognition to perform a task of structure damage Classification

In [5]:
import numpy as np

# Generate dummy data for demonstration purposes (replace this with your actual data)
def generate_dummy_data(samples=100, features=10):
    data = np.random.rand(samples, features)
    labels = np.random.randint(0, 2, size=samples)
    return data, labels

# Define the AIRS algorithm
class AIRS:
    def __init__(self, num_detectors=10, hypermutation_rate=0.1):
        self.num_detectors = num_detectors
        self.hypermutation_rate = hypermutation_rate
 
    def train(self, X, y):
        self.detectors = X[np.random.choice(len(X), self.num_detectors, replace=False)]
        self.labels = y
 
    def predict(self, X):
        predictions = []
        for sample in X:
            distances = np.linalg.norm(self.detectors - sample, axis=1)
            prediction = self.labels[np.argmin(distances)]
            predictions.append(prediction)
        return predictions

# Generate dummy data
data, labels = generate_dummy_data()

# Split data into training and testing sets
split_ratio = 0.8
split_index = int(split_ratio * len(data))
train_data, test_data = data[:split_index], data[split_index:]
train_labels, test_labels = labels[:split_index], labels[split_index:]

# Initialize and train AIRS
airs = AIRS(num_detectors=10, hypermutation_rate=0.1)
airs.train(train_data, train_labels)
       
# Test AIRS on the test set
predictions = airs.predict(test_data)

# Evaluate accuracy
accuracy = np.mean(predictions == test_labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.4


In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Load breast cancer dataset
data = load_breast_cancer()
X, y = data.data, data.target

# Define the AIRS algorithm
class AIRS:
    def __init__(self, num_detectors=10, hypermutation_rate=0.1):
        self.num_detectors = num_detectors
        self.hypermutation_rate = hypermutation_rate

    def train(self, X, y):
        self.detectors = X[np.random.choice(len(X), self.num_detectors, replace=False)]

    def predict(self, X):
        distances = np.linalg.norm(self.detectors[:, np.newaxis] - X, axis=2)
        predictions = np.argmin(distances, axis=0)
        return predictions
    
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train AIRS
airs = AIRS(num_detectors=10, hypermutation_rate=0.1)
airs.train(X_train, y_train)

# Test AIRS on the test set
predictions = airs.predict(X_test)

# Calculate accuracy
accuracy = np.mean(predictions == y_test) * 100
print(f"Accuracy: {accuracy:.2f}%")

8.Implement DEAP (Distributed Evolutionary Algorithms) using Python

In [2]:
import random
from deap import base, creator, tools, algorithms

# Define the evaluation function (minimize a simple mathematical function)
def eval_func(individual):
    # Example evaluation function (minimize a quadratic function)
    return sum(x ** 2 for x in individual),

# DEAP setup
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()

# Define attributes and individuals
toolbox.register("attr_float", random.uniform, -5.0, 5.0)  # Example: Float values between -5 and 5
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_float, n=3)  # Example: 3-dimensional individual
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# Evaluation function and genetic operators
toolbox.register("evaluate", eval_func)
toolbox.register("mate", tools.cxBlend, alpha=0.5)
toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=1, indpb=0.2)
toolbox.register("select", tools.selTournament, tournsize=3)

# Create population
population = toolbox.population(n=50)

# Genetic Algorithm parameters
cxpb = 0.5  # Crossover probability
mutpb = 0.1  # Mutation probability
generations = 20

# Run the algorithm
for gen in range(generations):
    offspring = algorithms.varAnd(population, toolbox, cxpb=cxpb, mutpb=mutpb)
    
    fits = toolbox.map(toolbox.evaluate, offspring)
    for fit, ind in zip(fits, offspring):
        ind.fitness.values = fit
    
    population = toolbox.select(offspring, k=len(population))

# Get the best individual after generations
best_ind = tools.selBest(population, k=1)[0]
best_fitness = best_ind.fitness.values[0]

print("Best individual:", best_ind)
print("Best fitness:", best_fitness)

Best individual: [-0.0016192386918194317, 0.00676216945691411, -0.0026095661572555218]
Best fitness: 5.515870523420053e-05


C:\Users\siddh\AppData\Local\Programs\Python\Python312\Lib\site-packages\deap\creator.py:185: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "


In [1]:
from deap import base, creator, tools, algorithms
import random
import numpy

# Define the fitness and individual classes
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()

# Attribute generator
toolbox.register("attr_bool", random.randint, 0, 1)

# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, 100)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

def evalOneMax(individual):
    return sum(individual),

# Operator registering
toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

pop = toolbox.population(n=300)
hof = tools.HallOfFame(1)
stats = tools.Statistics(lambda ind: ind.fitness.values)
stats.register("avg", numpy.mean)
stats.register("std", numpy.std)
stats.register("min", numpy.min)
stats.register("max", numpy.max)

pop, log = algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=40, 
                               stats=stats, halloffame=hof, verbose=True)

gen	nevals	avg    	std   	min	max
0  	300   	50.0933	5.1275	36 	66 
1  	151   	54.3267	3.70944	44 	66 
2  	194   	57.2133	3.34482	45 	69 
3  	176   	59.75  	3.28443	50 	71 
4  	198   	62.2633	3.48817	51 	72 
5  	170   	65.0367	3.41692	55 	76 
6  	187   	67.44  	3.35357	57 	79 
7  	176   	69.7967	3.35986	56 	82 
8  	173   	71.9933	3.0463 	63 	80 
9  	187   	73.79  	3.26485	62 	83 
10 	170   	75.8233	2.81166	66 	83 
11 	195   	77.57  	2.7151 	67 	86 
12 	164   	79.2467	2.73115	69 	87 
13 	212   	80.66  	2.76002	70 	88 
14 	184   	81.9633	2.82878	73 	89 
15 	200   	83.5267	2.44594	73 	89 
16 	187   	84.76  	2.33432	75 	91 
17 	161   	85.7733	2.2558 	76 	91 
18 	188   	86.47  	2.38937	77 	93 
19 	175   	87.6467	2.43895	76 	93 
20 	167   	88.8467	1.91568	81 	93 
21 	188   	89.5067	2.34875	77 	95 
22 	171   	90.6067	1.96942	82 	95 
23 	184   	91.09  	2.4702 	81 	96 
24 	175   	92.04  	2.52687	83 	96 
25 	166   	93.3067	2.48179	80 	98 
26 	187   	94.3267	2.48997	84 	98 
27 	203   	95.2767	2.3

Implement Ant colony optimization by solving the Traveling salesman problem using python Problem statement- A salesman needs to visit a set of cities exactly once and return to the original city. The task is to find the shortest possible route that the salesman can take to visit all the cities and return to the starting city

In [2]:
import numpy as np
import random
 
# Define the distance matrix (distances between cities)
# Replace this with your distance matrix or generate one based on your problem
# Example distance matrix (replace this with your actual data)
distance_matrix = np.array([
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
])
 
# Parameters for Ant Colony Optimization
num_ants = 10
num_iterations = 50
evaporation_rate = 0.5
pheromone_constant = 1.0
heuristic_constant = 1.0
 
# Initialize pheromone matrix and visibility matrix
num_cities = len(distance_matrix)
pheromone = np.ones((num_cities, num_cities))  # Pheromone matrix
visibility = 1 / distance_matrix  # Visibility matrix (inverse of distance)
 
# ACO algorithm
for iteration in range(num_iterations):
    ant_routes = []
    for ant in range(num_ants):
        current_city = random.randint(0, num_cities - 1)
        visited_cities = [current_city]
        route = [current_city]
        
        while len(visited_cities) < num_cities:
            probabilities = []
            for city in range(num_cities):
                if city not in visited_cities:
                    pheromone_value = pheromone[current_city][city]
                    visibility_value = visibility[current_city][city]
                    probability = (pheromone_value ** pheromone_constant) * (visibility_value ** heuristic_constant)
                    probabilities.append((city, probability))
            
            probabilities = sorted(probabilities, key=lambda x: x[1], reverse=True)
            selected_city = probabilities[0][0]
            route.append(selected_city)
            visited_cities.append(selected_city)
            current_city = selected_city
        
        ant_routes.append(route)
    
    # Update pheromone levels
    delta_pheromone = np.zeros((num_cities, num_cities))
    for ant, route in enumerate(ant_routes):
        for i in range(len(route) - 1):
            city_a = route[i]
            city_b = route[i + 1]
            delta_pheromone[city_a][city_b] += 1 / distance_matrix[city_a][city_b]
            delta_pheromone[city_b][city_a] += 1 / distance_matrix[city_a][city_b]
    
    pheromone = (1 - evaporation_rate) * pheromone + delta_pheromone
 
# Find the best route
best_route_index = np.argmax([sum(distance_matrix[cities[i]][cities[(i + 1) % num_cities]] for i in range(num_cities)) for cities in ant_routes])
best_route = ant_routes[best_route_index]
shortest_distance = sum(distance_matrix[best_route[i]][best_route[(i + 1) % num_cities]] for i in range(num_cities))
 
print("Best route:", best_route)
print("Shortest distance:", shortest_distance)


Best route: [2, 0, 1, 3]
Shortest distance: 80


C:\Users\pawar\AppData\Local\Temp\ipykernel_4340\3450148427.py:24: RuntimeWarning: divide by zero encountered in divide
  visibility = 1 / distance_matrix  # Visibility matrix (inverse of distance)
